# Generated by Django 3.2.4 on 2021-07-09 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('count_commits', models.PositiveIntegerField(default=0, verbose_name='Количество коммитов')),
                ('commit_hash', models.TextField(blank=True, verbose_name='Hash')),
                ('commit_branches_name', models.TextField(blank=True, verbose_name='Имя ветки/веток')),
                ('commit_author', models.TextField(blank=True, verbose_name='Автор')),
                ('commit_url', models.TextField(blank=True, verbose_name='Полный url адресс коммита')),
                ('commit_message', models.TextField(blank=True, verbose_name='Сообщение коммита')),
                ('commit_stats_add_lines', models.TextField(blank=True, verbose_name='Количество добавленных строк')),
                ('commit_stats_delete_lines', models.TextField(blank=True, verbose_name='Количество удаленных строк')),
                ('commit_stats_count_change_lines', models.TextField(blank=True, verbose_name='Общее количество изменений')),
                ('commit_stats_count_change_files', models.TextField(blank=True, verbose_name='Общее количество измененных файлов')),
            ],
            options={
                'verbose_name': 'Информация о коммитах',
                'verbose_name_plural': 'Данные о коммитах',
            },
        ),
        migrations.CreateModel(
            name='UrlRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_text', models.TextField(max_length=255, verbose_name='URL адрес репозитория')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'URL адреса',
                'verbose_name_plural': 'Список URL адресов',
            },
        ),
        migrations.CreateModel(
            name='ModifiedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('count_files', models.PositiveIntegerField(default=0, verbose_name='Количество измененных файлов')),
                ('file_name', models.TextField(blank=True, verbose_name='Имя файла')),
                ('file_full_path', models.TextField(blank=True, verbose_name='Полный путь')),
                ('file_status', models.TextField(blank=True, verbose_name='Статус')),
                ('file_stats_add_lines', models.TextField(blank=True, verbose_name='Количество добавленных строк')),
                ('file_stats_delete_lines', models.TextField(blank=True, verbose_name='Количество удаленных строк')),
                ('commit_hash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrate.commit', verbose_name='Принадлежат коммиту')),
            ],
            options={
                'verbose_name': 'Список изменений для каждого коммита',
                'verbose_name_plural': 'Список изменений',
            },
        ),
        migrations.AddField(
            model_name='commit',
            name='url_txt',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='integrate.urlrepository', verbose_name='Принадлежит репозиторию'),
        ),
    ]
