# Generated by Django 3.2.4 on 2021-07-09 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='url_txt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrate.urlrepository', verbose_name='Принадлежит репозиторию'),
        ),
    ]
