# Generated by Django 3.2.4 on 2021-07-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modifiedfile',
            options={'verbose_name': 'Список изменений для каждого коммита', 'verbose_name_plural': 'Список изменений'},
        ),
        migrations.AlterModelOptions(
            name='urlrepository',
            options={'verbose_name': 'URL адреса', 'verbose_name_plural': 'Список URL адресов'},
        ),
        migrations.AlterField(
            model_name='urlrepository',
            name='url_text',
            field=models.TextField(max_length=255, verbose_name='URL адрес репозитория'),
        ),
    ]
