# Generated by Django 3.1 on 2021-06-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='commit_hash',
        ),
    ]
