# Generated by Django 3.2.4 on 2021-07-09 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrate', '0002_alter_commit_url_txt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='modifiedfile',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='urlrepository',
            name='slug',
        ),
    ]
