# Generated by Django 3.1 on 2021-06-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrate', '0002_remove_url_commit_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_hash', models.CharField(blank=True, max_length=50)),
                ('commit_branches_name', models.CharField(blank=True, max_length=255)),
                ('commit_author', models.CharField(blank=True, max_length=30)),
                ('commit_url', models.CharField(blank=True, max_length=255)),
                ('commit_message', models.TextField(blank=True)),
                ('commit_stats_add_lines', models.CharField(blank=True, max_length=20)),
                ('commit_stats_delete_lines', models.CharField(blank=True, max_length=20)),
                ('commit_stats_count_change_lines', models.CharField(blank=True, max_length=20)),
                ('commit_stats_count_change_files', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ModifiedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=40)),
                ('file_full_path', models.CharField(blank=True, max_length=255)),
                ('file_status', models.CharField(blank=True, max_length=25)),
                ('file_stats_add_lines', models.CharField(blank=True, max_length=20)),
                ('file_stats_delete_lines', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UrlRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_text', models.CharField(help_text='Введите url адрес репозитория, к примеру: https://github.com/BOY4TOSTOBOY/OprosnikDjango', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='RepositoryGithub',
        ),
        migrations.DeleteModel(
            name='Url',
        ),
    ]
