# Generated by Django 3.2.4 on 2021-07-09 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrate', '0003_auto_20210709_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='url_txt',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='integrate.urlrepository', verbose_name='Принадлежит репозиторию'),
        ),
        migrations.AlterField(
            model_name='modifiedfile',
            name='commit_hash',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='integrate.commit', verbose_name='Принадлежат коммиту'),
        ),
    ]
