# Generated by Django 3.2.4 on 2021-06-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrate', '0003_auto_20210615_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='commit_author',
            field=models.CharField(blank=True, max_length=30, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='commit_branches_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя ветки/веток'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='commit_hash',
            field=models.CharField(blank=True, max_length=50, verbose_name='Hash'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='commit_message',
            field=models.TextField(blank=True, verbose_name='Сообщение коммита'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='commit_stats_add_lines',
            field=models.CharField(blank=True, max_length=20, verbose_name='Количество добавленных строк'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='commit_stats_count_change_files',
            field=models.CharField(blank=True, max_length=20, verbose_name='Общее количество измененных файлов'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='commit_stats_count_change_lines',
            field=models.CharField(blank=True, max_length=20, verbose_name='Общее количество изменений'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='commit_stats_delete_lines',
            field=models.CharField(blank=True, max_length=20, verbose_name='Количество удаленных строк'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='commit_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Полный url адресс коммита'),
        ),
        migrations.AlterField(
            model_name='modifiedfile',
            name='file_full_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='Полный путь'),
        ),
        migrations.AlterField(
            model_name='modifiedfile',
            name='file_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='modifiedfile',
            name='file_stats_add_lines',
            field=models.CharField(blank=True, max_length=20, verbose_name='Количество добавленных строк'),
        ),
        migrations.AlterField(
            model_name='modifiedfile',
            name='file_stats_delete_lines',
            field=models.CharField(blank=True, max_length=20, verbose_name='Количество удаленных строк'),
        ),
        migrations.AlterField(
            model_name='modifiedfile',
            name='file_status',
            field=models.CharField(blank=True, max_length=25, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='urlrepository',
            name='url_text',
            field=models.CharField(help_text='Введите url адрес репозитория, к примеру: https://github.com/BOY4TOSTOBOY/OprosnikDjango', max_length=255, verbose_name='URL адрес репозитория'),
        ),
    ]
