# Generated by Django 3.2.4 on 2021-07-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrate', '0004_auto_20210709_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalIteration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_iteration', models.IntegerField(blank=True, verbose_name='Количество записей в бд, принадлежащих коммиту')),
            ],
            options={
                'verbose_name': 'Тотал',
                'verbose_name_plural': 'Количество записей в бд за 1 итерацию',
            },
        ),
    ]
