# Generated by Django 3.2.4 on 2021-06-29 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrate', '0004_auto_20210629_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commit',
            options={'verbose_name': 'Информация о коммитах', 'verbose_name_plural': 'Данные о коммитах'},
        ),
        migrations.AlterModelOptions(
            name='modifiedfile',
            options={'verbose_name': 'Список изменений', 'verbose_name_plural': 'Список изменений'},
        ),
        migrations.AlterModelOptions(
            name='urlrepository',
            options={'verbose_name': 'URL адрес', 'verbose_name_plural': 'Список URL адресов'},
        ),
    ]
