# Generated by Django 3.2.4 on 2021-07-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrate', '0005_totaliteration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='totaliteration',
            options={'verbose_name': 'Количество записей в бд за 1 итерацию', 'verbose_name_plural': 'Total'},
        ),
    ]
