# Generated by Django 3.2.4 on 2021-07-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrate', '0006_alter_totaliteration_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commit',
            options={'verbose_name': 'GitHub - данные о коммитах', 'verbose_name_plural': 'GitHub - данные о коммитах'},
        ),
        migrations.AlterModelOptions(
            name='modifiedfile',
            options={'verbose_name': 'GitHub - изменения', 'verbose_name_plural': 'GitHub - модифицированные файлы'},
        ),
        migrations.AlterModelOptions(
            name='totaliteration',
            options={'verbose_name': 'Количество записей в бд за 1 итерацию', 'verbose_name_plural': 'Total записей'},
        ),
        migrations.AlterField(
            model_name='commit',
            name='commit_author',
            field=models.TextField(blank=True, null=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='commit_branches_name',
            field=models.TextField(blank=True, null=True, verbose_name='Имя ветки/веток'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='commit_hash',
            field=models.TextField(blank=True, null=True, verbose_name='Hash'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='commit_message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение коммита'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='commit_stats_add_lines',
            field=models.TextField(blank=True, null=True, verbose_name='Количество добавленных строк'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='commit_stats_count_change_files',
            field=models.TextField(blank=True, null=True, verbose_name='Общее количество измененных файлов'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='commit_stats_count_change_lines',
            field=models.TextField(blank=True, null=True, verbose_name='Общее количество изменений'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='commit_stats_delete_lines',
            field=models.TextField(blank=True, null=True, verbose_name='Количество удаленных строк'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='commit_url',
            field=models.TextField(blank=True, null=True, verbose_name='Полный url адресс коммита'),
        ),
        migrations.AlterField(
            model_name='modifiedfile',
            name='count_files',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Количество измененных файлов'),
        ),
        migrations.AlterField(
            model_name='modifiedfile',
            name='file_full_path',
            field=models.TextField(blank=True, null=True, verbose_name='Полный путь'),
        ),
        migrations.AlterField(
            model_name='modifiedfile',
            name='file_name',
            field=models.TextField(blank=True, null=True, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='modifiedfile',
            name='file_stats_add_lines',
            field=models.TextField(blank=True, null=True, verbose_name='Количество добавленных строк'),
        ),
        migrations.AlterField(
            model_name='modifiedfile',
            name='file_stats_delete_lines',
            field=models.TextField(blank=True, null=True, verbose_name='Количество удаленных строк'),
        ),
        migrations.AlterField(
            model_name='modifiedfile',
            name='file_status',
            field=models.TextField(blank=True, null=True, verbose_name='Статус'),
        ),
    ]
