# Generated by Django 3.2.4 on 2021-07-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrate', '0007_auto_20210710_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberOfCommits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_iteration', models.IntegerField(blank=True, verbose_name='Количество коммитов')),
            ],
            options={
                'verbose_name': 'Количество записей в бд',
                'verbose_name_plural': 'Number Commits',
            },
        ),
        migrations.CreateModel(
            name='NumberOfFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_iteration', models.IntegerField(blank=True, verbose_name='Количество файлов')),
            ],
            options={
                'verbose_name': 'Количество записей в бд',
                'verbose_name_plural': 'Number Files',
            },
        ),
        migrations.DeleteModel(
            name='TotalIteration',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='count_commits',
        ),
        migrations.RemoveField(
            model_name='modifiedfile',
            name='count_files',
        ),
    ]
